-- =========================================
-- 1. User & Access Management
-- =========================================

CREATE TABLE roles (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR(255),
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMP DEFAULT now(),
    updated_at  TIMESTAMP DEFAULT now()
);

CREATE TABLE users (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id        INTEGER,
    username       VARCHAR(255) NOT NULL UNIQUE,
    password  VARCHAR(255),
    email          VARCHAR(255) UNIQUE,
    prefix_id      INTEGER,
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    phone          VARCHAR(255),
    is_active      BOOLEAN DEFAULT true,
    last_login     TIMESTAMP,
    created_by     INTEGER,
    updated_by     INTEGER,
    created_at     TIMESTAMP DEFAULT now(),
    updated_at     TIMESTAMP DEFAULT now()
);

CREATE TABLE password_reset_tokens (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER,
    otp_code    VARCHAR(255),
    expires_at  TIMESTAMP,
    is_used     BOOLEAN,
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMP DEFAULT now(),
    updated_at  TIMESTAMP DEFAULT now()
);

CREATE TABLE addresses (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER,
    street        VARCHAR(255),
    sub_district  VARCHAR(255),
    district      VARCHAR(255),
    province      VARCHAR(255),
    zip_code      VARCHAR(255),
    created_by    INTEGER,
    updated_by    INTEGER,
    created_at    TIMESTAMP DEFAULT now(),
    updated_at    TIMESTAMP DEFAULT now()
);

-- =========================================
-- 2. Products & Inventory
-- =========================================

CREATE TABLE categories (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL UNIQUE,
    slug           VARCHAR(255),
    category_code  VARCHAR(255) NOT NULL UNIQUE,
    is_active      BOOLEAN DEFAULT true,
    created_by     INTEGER,
    updated_by     INTEGER,
    created_at     TIMESTAMP DEFAULT now(),
    updated_at     TIMESTAMP DEFAULT now()
);

CREATE TABLE products (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code   VARCHAR(255) NOT NULL UNIQUE,
    category_id  INTEGER,
    name         VARCHAR(255) NOT NULL UNIQUE,
    description  TEXT,
    base_price   NUMERIC(10,2),
    image_path   VARCHAR(255),
    is_active    BOOLEAN DEFAULT true,
    created_by   INTEGER,
    updated_by   INTEGER,
    created_at   TIMESTAMP DEFAULT now(),
    updated_at   TIMESTAMP DEFAULT now()
);

CREATE TABLE product_variants (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     INTEGER,
    sku_code       VARCHAR(255) UNIQUE NOT NULL,
    size           VARCHAR(255),
    stock_quantity INTEGER,
    created_by     INTEGER,
    updated_by     INTEGER,
    created_at     TIMESTAMP DEFAULT now(),
    updated_at     TIMESTAMP DEFAULT now()
);

-- =========================================
-- 3. Orders & Statuses
-- =========================================

CREATE TABLE order_statuses (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR(255) NOT NULL UNIQUE,
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMP DEFAULT now(),
    updated_at  TIMESTAMP DEFAULT now()
);

CREATE TABLE payment_statuses (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMP DEFAULT now(),
    updated_at  TIMESTAMP DEFAULT now()
);

CREATE TABLE orders (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           INTEGER,
    order_status_id   INTEGER,
    payment_intent_id VARCHAR(255),
    payment_status_id INTEGER,
    total_amount      NUMERIC(10,2),
    shipping_address  JSONB,
    order_code        VARCHAR(255) NOT NULL UNIQUE,
    created_by        INTEGER,
    updated_by        INTEGER,
    created_at        TIMESTAMP DEFAULT now(),
    updated_at        TIMESTAMP DEFAULT now()
);

CREATE TABLE order_items (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    INTEGER,
    variant_id  INTEGER,
    quantity    INTEGER,
    unit_price  NUMERIC(10,2),
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMP DEFAULT now(),
    updated_at  TIMESTAMP DEFAULT now()
);

-- =========================================
-- 4. Cart
-- =========================================

CREATE TABLE carts (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER,
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMP DEFAULT now(),
    updated_at  TIMESTAMP DEFAULT now()
);

CREATE TABLE cart_items (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id     INTEGER,
    variant_id  INTEGER,
    quantity    INTEGER,
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMP DEFAULT now(),
    updated_at  TIMESTAMP DEFAULT now()
);

-- =========================================
-- 5. Discounts
-- =========================================

CREATE TABLE discount_types (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount_name  VARCHAR(255) NOT NULL UNIQUE,
    created_by     INTEGER,
    updated_by     INTEGER,
    created_at     TIMESTAMP DEFAULT now(),
    updated_at     TIMESTAMP DEFAULT now()
);

CREATE TABLE discounts (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount_type_id INTEGER,
    code             VARCHAR(255) UNIQUE,
    value            NUMERIC(10,2),
    expiry_date      TIMESTAMP,
    created_by       INTEGER,
    updated_by       INTEGER,
    created_at       TIMESTAMP DEFAULT now(),
    updated_at       TIMESTAMP DEFAULT now()
);

-- =========================================
-- 6. System & Logs
-- =========================================

CREATE TABLE reviews (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  INTEGER,
    user_id     INTEGER,
    rating      INTEGER,
    comment     TEXT,
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMP DEFAULT now(),
    updated_at  TIMESTAMP DEFAULT now()
);

CREATE TABLE prefixes (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prefix_name  VARCHAR(255) NOT NULL,          -- เช่น นาย, นาง, นางสาว ฯลฯ
    is_active    BOOLEAN DEFAULT true,
    created_by   INTEGER,
    updated_by   INTEGER,
    created_at   TIMESTAMP DEFAULT now(),
    updated_at   TIMESTAMP DEFAULT now()
);

CREATE TABLE activity_logs (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER,
    action       VARCHAR(255),
    entity_name  VARCHAR(255),
    entity_id    VARCHAR(255),
    details      JSONB,
    "timestamp"  TIMESTAMP DEFAULT now(),
    created_by   INTEGER,
    updated_by   INTEGER,
    created_at   TIMESTAMP DEFAULT now(),
    updated_at   TIMESTAMP DEFAULT now()
);

