-- =========================================
-- 1. User & Access Management
-- =========================================

CREATE TABLE roles (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR(255),
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMP DEFAULT now(),
    updated_at  TIMESTAMP DEFAULT now()
);

CREATE TABLE users (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id        INTEGER,
    username       VARCHAR(255) NOT NULL UNIQUE,
    password  VARCHAR(255),
    email          VARCHAR(255) UNIQUE,
    prefix_id      INTEGER,
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    phone          VARCHAR(255),
    is_active      BOOLEAN DEFAULT true,
    last_login     TIMESTAMP,
    created_by     INTEGER,
    updated_by     INTEGER,
    created_at     TIMESTAMP DEFAULT now(),
    updated_at     TIMESTAMP DEFAULT now()
);

CREATE TABLE password_reset_tokens (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER,
    otp_code    VARCHAR(255),
    expires_at  TIMESTAMP,
    is_used     BOOLEAN,
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMP DEFAULT now(),
    updated_at  TIMESTAMP DEFAULT now()
);

CREATE TABLE addresses (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER,
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    phone         VARCHAR(50),
    street        VARCHAR(255),
    sub_district  VARCHAR(255),
    district      VARCHAR(255),
    province      VARCHAR(255),
    zip_code      VARCHAR(255),
    created_by    INTEGER,
    updated_by    INTEGER,
    created_at    TIMESTAMP DEFAULT now(),
    updated_at    TIMESTAMP DEFAULT now()
);

-- =========================================
-- 2. Products & Inventory
-- =========================================

CREATE TABLE categories (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name           VARCHAR(255) NOT NULL UNIQUE,
    category_code  VARCHAR(255) UNIQUE,
    is_active      BOOLEAN DEFAULT true,
    created_by     INTEGER,
    updated_by     INTEGER,
    created_at     TIMESTAMP DEFAULT now(),
    updated_at     TIMESTAMP DEFAULT now()
);

CREATE TABLE genders (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gender_name           VARCHAR(50) NOT NULL UNIQUE, -- Men, Women, Unisex, Kids
    slug           VARCHAR(50),                 -- men, women
    created_by     INTEGER,
    updated_by     INTEGER,
    created_at     TIMESTAMP DEFAULT now(),
    updated_at     TIMESTAMP DEFAULT now()
);

CREATE TABLE products (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code   VARCHAR(255) NOT NULL UNIQUE,
    
    -- 1. Foreign Keys: ควรบังคับใส่ เพื่อไม่ให้สินค้าลอยแพ
    category_id    INTEGER NOT NULL, 
    gender_id      INTEGER NOT NULL,
    
    product_name   VARCHAR(255) NOT NULL UNIQUE,
    description    TEXT, -- อันนี้ปล่อย NULL ได้ (บางทีขี้เกียจใส่คำบรรยาย)
    
    -- 2. Price: ห้ามว่างเด็ดขาด เดี๋ยวคำนวณเงินไม่ได้
    base_price     NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    
    image_path     VARCHAR(255), -- ปล่อย NULL ได้ (ถ้ายังไม่มีรูป ให้ Frontend โชว์รูป Placeholder แทน)
    
    -- 3. Boolean: บังคับ NOT NULL แต่ใส่ Default ให้
    best_seller    BOOLEAN NOT NULL DEFAULT false,
    is_active      BOOLEAN NOT NULL DEFAULT true,
    
    -- 4. Audit: ควรมีคนสร้างเสมอ
    created_by     INTEGER, -- อาจจะยอมให้ NULL ได้ถ้าเป็นการ Seed ข้อมูลระบบ แต่ถ้าใช้งานจริงควร NOT NULL
    updated_by     INTEGER,
    
    created_at     TIMESTAMP NOT NULL DEFAULT now(),
    updated_at     TIMESTAMP NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMP,
);

CREATE TABLE product_variants (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     INTEGER,
    sku_code       VARCHAR(255) UNIQUE NOT NULL,
    size           VARCHAR(255),
    stock_quantity INTEGER,
    deleted_at     TIMESTAMP,
    created_by     INTEGER,
    updated_by     INTEGER,
    created_at     TIMESTAMP DEFAULT now(),
    updated_at     TIMESTAMP DEFAULT now()
);

-- =========================================
-- 3. Orders & Statuses
-- =========================================

CREATE TABLE order_statuses (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR(255) NOT NULL UNIQUE,
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMP DEFAULT now(),
    updated_at  TIMESTAMP DEFAULT now()
);

CREATE TABLE payment_statuses (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMP DEFAULT now(),
    updated_at  TIMESTAMP DEFAULT now()
);

CREATE TABLE orders (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           INTEGER,
    order_status_id   INTEGER,
    payment_intent_id VARCHAR(255),
    payment_status_id INTEGER,
    total_amount      NUMERIC(10,2),
    shipping_address  JSONB,
    order_code        VARCHAR(255) NOT NULL UNIQUE,
    tracking_number   VARCHAR(255), -- ไม่ต้องใส่ NOT NULL
    cancelled_reason  TEXT,       -- เก็บเหตุผล (Null ได้ ถ้ายังไม่ยกเลิก)
    cancelled_at      TIMESTAMP,  -- เก็บเวลาที่กดยกเลิก
    cancelled_by      INTEGER,    -- เก็บ user_id ของคนที่กด (เผื่อ Admin กดให้)
    created_by        INTEGER,
    updated_by        INTEGER,
    created_at        TIMESTAMP DEFAULT now(),
    updated_at        TIMESTAMP DEFAULT now()
);

CREATE TABLE order_items (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    INTEGER,
    variant_id  INTEGER,
    quantity    INTEGER,
    unit_price  NUMERIC(10,2),
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMP DEFAULT now(),
    updated_at  TIMESTAMP DEFAULT now()
);

-- =========================================
-- 4. Cart
-- =========================================

CREATE TABLE carts (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER,
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMP DEFAULT now(),
    updated_at  TIMESTAMP DEFAULT now()
);

CREATE TABLE cart_items (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id     INTEGER,
    variant_id  INTEGER,
    quantity    INTEGER,
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMP DEFAULT now(),
    updated_at  TIMESTAMP DEFAULT now()
);

-- =========================================
-- 5. Discounts
-- =========================================

CREATE TABLE discount_types (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount_name  VARCHAR(255) NOT NULL UNIQUE,
    created_by     INTEGER,
    updated_by     INTEGER,
    created_at     TIMESTAMP DEFAULT now(),
    updated_at     TIMESTAMP DEFAULT now()
);

CREATE TABLE discounts (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount_type_id INTEGER,
    code             VARCHAR(255) UNIQUE,
    value            NUMERIC(10,2),
    expiry_date      TIMESTAMP,
    created_by       INTEGER,
    updated_by       INTEGER,
    created_at       TIMESTAMP DEFAULT now(),
    updated_at       TIMESTAMP DEFAULT now()
);

-- =========================================
-- 6. System & Logs
-- =========================================

CREATE TABLE reviews (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  INTEGER,
    user_id     INTEGER,
    rating      INTEGER,
    comment     TEXT,
    created_by  INTEGER,
    updated_by  INTEGER,
    created_at  TIMESTAMP DEFAULT now(),
    updated_at  TIMESTAMP DEFAULT now()
);

CREATE TABLE prefixes (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prefix_name  VARCHAR(255) NOT NULL,          -- เช่น นาย, นาง, นางสาว ฯลฯ
    is_active    BOOLEAN DEFAULT true,
    created_by   INTEGER,
    updated_by   INTEGER,
    created_at   TIMESTAMP DEFAULT now(),
    updated_at   TIMESTAMP DEFAULT now()
);

CREATE TABLE activity_logs (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER,
    action       VARCHAR(255),
    entity_name  VARCHAR(255),
    entity_id    VARCHAR(255),
    details      JSONB,
    "timestamp"  TIMESTAMP DEFAULT now(),
    created_by   INTEGER,
    updated_by   INTEGER,
    created_at   TIMESTAMP DEFAULT now(),
    updated_at   TIMESTAMP DEFAULT now()
);

